### PR TITLE
Add type of launch to the cards

### PR DESCRIPTION
**Pull request by wantedsystem**
Result=>
Capture d’écran 2021-11-26 à 19 18 09

### CODE REVIEW

**Review by dkent600 — CHANGES_REQUESTED** [review]
Can you please add this one to this PR?

https://github.com/PrimeDAO/prime-launch-dapp/issues/514

**Review by dkent600 — CHANGES_REQUESTED** [review]
Needs to look like the mock.  There is too much horizontal gap between the new type and the project title

**Comment by wantedsystem** [comment]
> Needs to look like the mock. There is too much horizontal gap between the new type and the project title

@dkent600  Forgot to put the last screenshot 
Capture d’écran 2021-11-30 à 11 16 12

**Review by dkent600 — CHANGES_REQUESTED** [review]
Please take a close look at the mock.  Still does not conform.

image

**Comment by wantedsystem** [comment]
Result =>
Capture d’écran 2021-12-02 à 15 08 30

**Review by dkent600 — CHANGES_REQUESTED** [review]
Has to look much more like the mock.

**Comment by wantedsystem** [comment]
Capture d’écran 2021-12-03 à 12 19 25

I think it's okey now @dkent600 ?

**Comment by dkent600** [comment]
Still isn't perfect, but I'm going to approve anyway

**Review by dkent600 — APPROVED** [review]

**Pull request merged**
